/**
 * Mission page copy. Plain text with \n for line breaks and \n\n for paragraph
 * gaps, rendered with `whitespace-pre-line`. This mirrors the shape the admin
 * panel (Payload plain-text fields) will produce, so the swap later is trivial.
 */
export const missionPage = {
  missionHeading: "Mission",
  missionStatement:
    "Grace House NorCal is a nonprofit, faith-based discipleship program in Sacramento, California, dedicated to helping men and women overcome life-controlling challenges, rebuild their lives, and find lasting hope through faith, personal accountability, and strong moral values. We value each individual and build lasting relationships while partnering with agencies throughout the greater Sacramento area and maintaining established relationships with the court systems across multiple counties to provide individuals with opportunities for meaningful change and restoration. Through these partnerships and our commitment to discipleship, we equip our spiritual family with the knowledge, guidance, and practical tools needed to confront life’s challenges, break destructive cycles, and become productive members of their communities. Our mission is to transform lives, make our communities safer, see families restored, and give hope to the hopeless.",
  whyHeading: "Why Grace House",
  whyBody:
    "While the rewards for recovery are vast, we have a philosophy that we help our residents realize, and that is a four-step process that consists of the following pillars of recovery. First, we feel that the number one thing our residents gain is self-forgiveness. They are forgiving themselves for all the pain and misery they cause their families and themselves while in their addiction. We believe that God’s timing works to perfection every time by letting things happen in his time and not forcing things to happen before we are ready for them. They are becoming a giver and not a taker. Addiction steals more than a person. It steals love, joy, affection, peace, and harmony. They are giving self, encouragement, and all the good things they deserve to experience. And last but not least is the pillar of restoration which happens when they work through the first three pillars. Restoration of families and friends, husbands and wives, children and parents.\n\nGrace House has a fantastic success rate that is above average. We pride ourselves in being a community, and most of our past residents stay connected with us and continue to further their recovery in many different ways after graduation. Sometimes this might look like coming back and teaching some of our classes or sitting in on those classes being taught, showing up to our community outreaches, and sponsoring current residents. We are very proud of our successes and look forward to continuing to serve our community the best way we know how.",
};
