/**
 * Mission page copy. Plain text with \n for line breaks and \n\n for paragraph
 * gaps, rendered with `whitespace-pre-line`. This mirrors the shape the admin
 * panel (Payload plain-text fields) will produce, so the swap later is trivial.
 */
export const missionPage = {
  missionHeading: "Mission",
  missionStatement:
    "Grace House NorCal is a faith-based discipleship program in Sacramento, California, dedicated to helping men and women overcome life’s challenges, rebuild their lives, and discover lasting hope through spiritual growth, personal accountability, and strong moral values. Through compassionate support and lasting relationships, we strive to see families restored and give hope to the hopeless.\n\nBuilding on this foundation, we value each individual and work to create an environment where meaningful change and lasting restoration can take place. We partner with agencies throughout the greater Sacramento area and maintain established relationships with court systems across multiple counties, providing individuals with opportunities to address the challenges in their lives and move toward a more productive future. Through these partnerships and our commitment to discipleship, we equip our spiritual family with the knowledge, guidance, and practical tools needed to confront life’s challenges, break destructive cycles, and become productive members of their communities. Our goal is not simply to help individuals complete a program, but to establish a foundation for continued growth and positive change.\n\nThe strength of our community extends well beyond graduation. Many former residents remain connected to Grace House and continue their recovery and personal growth in a variety of ways. Some return to teach or participate in classes, support community outreach efforts, or sponsor current residents. These continuing relationships are an important part of the Grace House community and reflect the lasting impact of the program. We are proud of the lives transformed through Grace House and remain committed to serving individuals, families, and communities throughout the Sacramento region.",
};
